import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import Starfield from "@/components/Starfield";
import UserProvider from "@/providers/UserProvider";
import "./globals.css";
import NailongPlanet from "@/components/NailongPlanet";

export const metadata: Metadata = {
  title: "Home | NaiX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black min-h-screen">
        <UserProvider>
          <Navigation />

          <main className="relative z-5">
            <NailongPlanet />
            <Starfield />
            {children}
          </main>
        </UserProvider>
      </body>
    </html>
  );
}