import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import "./globals.css";

export const metadata: Metadata = {
	title: "Home | Nailong Express",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
    <html lang="en">
      <body className="bg-black min-h-screen">
        <Navigation />
        <main className="relative z-5">{children}</main>
      </body>
    </html>
	);
}
